name: 'whitegoods_inventory'
version: '1.0.0'
config-version: 2

profile: 'whitegoods_inventory'

model-paths: ["models"]
test-paths: ["tests"]

models:
  whitegoods_inventory:
    staging:
      +schema: staging
      +materialized: view
      +database: TRANSFORM
    intermediate:
      +schema: intermediate
      +materialized: table
      +database: TRANSFORM
    marts:
      +schema: marts
      +materialized: table
      +database: ANALYTICS