select
    product_id,
    product_name,
    sku,
    category,
    brand,
    supplier_id,
    unit_cost,
    rrp,
    reorder_point,
    reorder_qty,
    location_id,
    location_name,
    location_type,
    city,
    qty_on_hand,
    qty_on_hand * unit_cost   as stock_value_cost,
    qty_on_hand * rrp         as stock_value_rrp,
    is_below_reorder_point,
    last_event_at
from {{ ref('int_inventory_current') }}