version: 2

sources:
  - name: inventory
    database: RAW
    schema: inventory
    tables:
      - name: products
        loaded_at_field: _loaded_at
        freshness:
          warn_after: {count: 24, period: hour}
      - name: locations
      - name: suppliers
      - name: purchase_orders
        loaded_at_field: _loaded_at
        freshness:
          warn_after: {count: 24, period: hour}
      - name: purchase_order_lines
        loaded_at_field: _loaded_at
        freshness:
          warn_after: {count: 24, period: hour}
      - name: inventory_events
        loaded_at_field: _loaded_at
        freshness:
          warn_after: {count: 1, period: hour}